### ISSUE TITLE
Starfinder>Biohacker: Microlab + Biohack

### ISSUE THREAD

**Issue by Ravien** [dyslexic-charactersheets/pages#10]
Microlab:
For the creature identification: Should call out Life science (if living) or Physical Science (if unliving)

The attunement is 3+key ability mod max creatures

Biohacks:
On the minor, basic booster, + basic inhibitor, should note that you pick one of the listed items? 

Spark of Ingenuity - this is a limited use ability, 1/day, 2/day @9th and 3/day @15th. Also Instinctive Lv9 enhancement - Inhibitor biohack gains off-target OR dazzled. The language is really messy on this one

**Comment by marcus-downing** [comment]
Resolved.
