### ISSUE TITLE
Typo in pf2 diabolic bloodline

### ISSUE THREAD

**Issue by christof337** [dyslexic-charactersheets/pages#14]
There is a typo in the pf2 diabolic bloodline (diabolic edict power) : 
    Pathfinder 2e/core/class/sorcerer/bloodline/sorcerer-bloodline-diabolic

The text says `Otherwise, they take a -1 penalty to related attack **roles** and skill checks.` where it should states `Otherwise, they take a -1 penalty to related attack **rolls** and skill checks.`, with `rolls` instead of `roles`

Thanks

**Comment by marcus-downing** [comment]
Well spotted!

I've fixed that, it'll be released with the archetypes I'm currently working on.

**Comment by christof337** [comment]
see https://github.com/dyslexic-charactersheets/lib-charactersheets/pull/9
