### ISSUE TITLE
Error in throw bomb (alchemist, pf2)

### ISSUE THREAD

**Issue by christof337** [dyslexic-charactersheets/pages#16]
Hi.

In the alchemist sheet, under `alchemist class DC`, the `throw bomb` entry asks for a `STR` modifier, whereas as a thrown weapon, the bomb uses the dexterity modifier for the attack roll. 
It should be `DEX` instead of `STR`.

![image](https://user-images.githubusercontent.com/4980937/102996037-9cfd9080-4522-11eb-8510-b643cfbbc5d8.png)

**Comment by marcus-downing** [comment]
You're right. I got confused because thrown weapons can add `STR` to damage.
