### ISSUE TITLE
Numerous Typos

### ISSUE THREAD

**Issue by christof337** [dyslexic-charactersheets/pages#28]
First, thanks for the great work on the archetypes 👍 
(and the headsup on Patreon, really appreciated 🥰 )

I couldn't help from noticing a few typos while translating. I do hope the label only will be enough for you to fix it (without the context), with an old school yet powerful "Ctrl+F/H" 

1. **Avalance** Strike ▶️ **Avalanche** Strike
2. As long as your **mvoe** is at leat 20ft, take a 10ft step ▶️ As long as your **speed** is at leat 20ft, take a 10ft step
3. ~**Dyslexie** Font ▶️ **Dyslexic** Font ?~
4. When a target critically fails their initial saving throw against your poison, an **adjacenmt** creature is exposed as well. ▶️ When a target critically fails their initial saving throw against your poison, an **adjacent** creature is exposed as well.

The following might have been fixed already, but still somehow appear on the translation platform. I put them here just in case
2. **Runescanned** ▶️ **Runescarred**
3. Expert **Disassemblky** ▶️ Expert **Disassembly**
4. Heal an **animaul** up to 30ft ▶️ Heal an **animal** up to 30ft 
5. **Resitance** ▶️ **Resistance**
6. Druid Class DC ▶️ [nothing]/doesn't exist (since errata 1)
7. Reduce **resitances** (see below) ▶️ Reduce **resistances** (see below)
8. **An** a critical hit with a poisoned dart, if the target fails the poison's initial save, they critically fails instead. ▶️ **On** a critical hit with a poisoned dart, if the target fails the poison's initial save, they critically fails instead.

**Comment by marcus-downing** [comment]
> Dyslexie Font

This one is actually correct. It's the name of the font.

**Comment by christof337** [comment]
added
8. **An** a critical hit with a poisoned dart, if the target fails the poison's initial save, they critically fails instead. ▶️ **On** a critical hit with a poisoned dart, if the target fails the poison's initial save, they critically fails instead.

**Comment by marcus-downing** [comment]
I believe these are all fixed, on the dev site now.
