### ISSUE TITLE
[PF2] Request: Click on proficiency indicators to cycle through ranks

### ISSUE THREAD

**Issue by LonePaladin** [dyslexic-charactersheets/pages#30]
The PF2 sheet has many areas where you can indicate your proficiency rank in a skill or attack or other ability, using a diamond pattern. On some pages, it is demonstrated that this uses a series of filled-in squares to indicate the rank: one for Trained, two for Expert, and so on.

The HTML sheet would be a bit more useful if you could click on these indicators to cycle through these four levels, with a fifth click returning the indicator to a blank state. Sort of like the check-boxes you find on the sheet, just with five states instead of two.

**Comment by marcus-downing** [comment]
I'm working on making everything editable right now. What I've gone with for the proficiency is a menu:
![183300869_10158236305717894_720483775720706524_n](https://user-images.githubusercontent.com/964232/126896901-b0ec2f93-8638-4ed5-8ae2-14aa2ccd4c3f.jpg)

**Comment by LonePaladin** [comment]
That looks really sharp -- and looks more intuitive than my suggestion.

**Comment by marcus-downing** [comment]
This was done.
