### ISSUE TITLE
[PF2] Wizard Advancement Page Shows Sorcerer Options

### ISSUE THREAD

**Issue by LonePaladin** [dyslexic-charactersheets/pages#32]
The advancement page for a Wizard character shows options for a Sorcerer, like Bloodline abilities.

![image](https://user-images.githubusercontent.com/37523352/126886832-64f7d143-95a4-48e5-b14d-0d473989d67b.png)

**Comment by marcus-downing** [comment]
I think I must have already fixed this, because it isn't happening on my local version.

I'll keep this issue open until I've confirmed the fix on live, though.

**Comment by marcus-downing** [comment]
Fixed.
