### ISSUE TITLE
[PF2] Spellbook Page - VSM Checkboxes Don't Fill Properly

### ISSUE THREAD

**Issue by LonePaladin** [dyslexic-charactersheets/pages#33]
On the spellbook page, if you click on any of the check-boxes (for V, S, M) on the right column, it fills in the box on the corresponding space on the _center_ column.

![Screenshot 2021-07-25 200912](https://user-images.githubusercontent.com/37523352/126920722-76aefa3d-e665-4273-94a7-eefc97b7e72a.png)

On the left column, all of the VSM check-boxes fill in the boxes on the first item in that column.

![Screenshot 2021-07-25 201821](https://user-images.githubusercontent.com/37523352/126920781-6accc770-695f-45e4-9baf-5867fb186fc1.png)

**Comment by LonePaladin** [comment]
To clarify, this is the _first_ spellbook page, where it includes a focus spell. The _second_ spellbook page doesn't even respond when you click on the check-boxes.

EDIT: I just figured out, all of the check-boxes on the second spellbook page are toggling the check-boxes on the _first_ page, specifically the top entry in the center column.

**Comment by marcus-downing** [comment]
It's clearly using the wrong IDs for them. Rather it's using the same ID for all of them, when it should be picking up the spell entry's ID each time. I'll fix this.

**Comment by marcus-downing** [comment]
Fixed.
