### ISSUE TITLE
[PF2] Request: Additional Build Options from Newer Books

### ISSUE THREAD

**Issue by LonePaladin** [dyslexic-charactersheets/pages#35]
Now that Secrets of Magic is out, I'd love to see the Magus and Summoner sheets added -- because _of course_ one of my players had to take one of the new classes. Granted, this also means the Gunslinger and Inventor should be considered for addition Soon™, along with the Thaumaturge and Psychic later.

I know, I know, I ask for a lot.

**Comment by marcus-downing** [comment]
Of course I'm working on the Magus and Summoner. If you look at the facebook group you'll see various pictures I've posted of the work in progress. Once it's sufficiently ready, I'll put it on the dev site for everyone to try.

**Comment by marcus-downing** [comment]
This Trello board shows what I'm working on.
https://trello.com/b/2TiqrLr0/dyslexic-character-sheets

**Comment by LonePaladin** [comment]
> If you look at the facebook group

That's why I didn't know.

**Comment by marcus-downing** [comment]
@LonePaladin The preview is on the dev site now: https://dev.dyslexic-charactersheets.com/
