### ISSUE TITLE
[PF2] Adding resistances box

### ISSUE THREAD

**Issue by Rowiz49** [dyslexic-charactersheets/pages#36]
It would be great if you could add a resistances box in the defense section of the sheets.

**Comment by marcus-downing** [comment]
Which game is this?

**Comment by Rowiz49** [comment]
In Pathfinder 2e

**Comment by marcus-downing** [comment]
I'm not sure there's any room. That page is already quite cramped.

**Comment by Rowiz49** [comment]
Maybe we could reduce the current hitpoints box, as it's very long, and add a simple Resistances line in the same style as the deity or languages box?
