### ISSUE TITLE
Wand charges x30 and not x50 ?

### ISSUE THREAD

**Issue by dcpc007** [dyslexic-charactersheets/pages#5]
I generate a 3.5 rogue sheet with wand/potion and i see in wand that there is 30 boxe's for charges. But a wand is 50 by default.

An idea, i track my charge use by a Scheme on A box of 5 charge like in this image : http://www.fabriceaujapon.com/blog/uploads/images/compter.jpg (the 2nd line). Maybe you can make only 5 boxes with one diag in light gray, and players could overwrite on it with black pen.

**Comment by marcus-downing** [comment]
An interesting thought. The two questions are whether people will understand the proposed scheme, and whether it's flexible enough.

Most people won't be familiar with the Japanese version, or the middle option. It might be a better system in abstract, but without familiarity people won't use the counter correctly, and will be frustrated and confused. The top option is one that should be familiar to most people, arguably more so than the current grid of checkboxes.

The checkbox grid are used in a lot more cases than wands, including:
 - ammunition
 - spells per day
 - rounds of ability per day (eg rage)

These break down into two types: counting up from zero, and counting down to zero. At present people can use either system, which is a double-edged sword as it can lead to confusion when people look at each other's sheets. Your proposed version would only be suitable to an additive use, as you can't safely erase part of a block. For some uses that might be preferable.

Do you mind if I post the mockup on the Facebook group and see what people think?

**Comment by marcus-downing** [comment]
As for why it's 30 rather than 50: limited space. That's it.

**Comment by dcpc007** [comment]
for explanation you could take the image i took (and keep only 2nd line ?? in the help ?

**Comment by marcus-downing** [comment]
I've posted to Facebook for opinions:
https://www.facebook.com/groups/dyslexiccharactersheets/permalink/1817094855248167/

**Comment by marcus-downing** [comment]
The consensus among users on Facebook is to keep the checkboxes (but to have the right number of them).

I'm not obligated to do what people on Facebook tell me to do, of course. I may try making a mockup using your suggestion to see if that affects the debate.

**Comment by dcpc007** [comment]
I try to make the progressive image for "how to count", don't find on internet i launch gimp :)

**Comment by dcpc007** [comment]
![comptebatons5](https://user-images.githubusercontent.com/847516/32281753-118e49da-bf20-11e7-8967-fa969558976a.png)

**Comment by marcus-downing** [comment]
The problem with that form of counter is that you needed to explain it. It isn't clear to somebody who hasn't seen the explanation.

**Comment by marcus-downing** [comment]
It's true that there are some parts of my character sheets that take a little getting used to - such as the bonus spells lines - but I try to keep them clear.

**Comment by marcus-downing** [comment]
![wand-counters](https://user-images.githubusercontent.com/964232/32302496-e906e298-bf5a-11e7-9c80-d284be90ed79.png)

Here's a mockup of what the fingers-style counter might look like.

**Comment by marcus-downing** [comment]
The poll on Facebook was clearly in favour of sticking with checkboxes rather than any other options. I hope you don't mind, but that's what I've gone for.

I've adjusted all the sheets with wands on so that there's 50 checkboxes, both for Pathfinder and 3.5. It'll be included when I publish the next version (in maybe a month or two).

**Comment by dcpc007** [comment]
Late but a friend show me another solution : make 25 checkboxes and use a double write like "/" = 1 use and "X" = 2 uses (by adding the "\\")
take less space, easy to use and near easy to count charges

**Comment by marcus-downing** [comment]
That would make it harder to erase a precise amount. And again, if I need to _explain_ to people how to use it then it's not as good.

**Comment by dcpc007** [comment]
I speak only for wand charges in this issue ... 
When do you want to remove part of used charges ? or when can you "add" a charge in a wand ?
For me you have only to add uses and when all boxes are double checked, wand is empty ... 

What is complicated here ? 
Ha maybe guess how to count 50 charges with 25 boxes ? 
Hum yes ... not all of us come from Harvard... and it seems a complicated math problem ... how can i count to 50 with 25 items... mmmhhhhh ??? need a tutorial. Ok, let's stop that here, go for amibe's IQ players :)

I'll see how is the sheet with (50 x wand lines) boxes.

Spoil and warn : extremely complicated solution under this line, stop here is you don't understand above :)
For my personal sheet, i use 2 fields : 
- current charges left (written by hand with numbers) (at the start of envening)
- juste near of it i use my square 5 lines to count quickly during fights how many i use.

And careful : after the game or during pauses, i erase and compute the new number of current charges with nenCurrent = (oldCurrent - used) ...

Why : using paper and pencil paper, i try to limit rubbing out sheet each 5 min (slow and damage paper)
With this, it's really quick to count charge during fight, and have a real number to "see" the number at the begin or end.
![dc_wand_count](https://user-images.githubusercontent.com/847516/32749011-3d7e372e-c8be-11e7-88eb-a3e7b347e387.png)
