### ISSUE TITLE
No spells for skald

### ISSUE THREAD

**Issue by myrrien** [dyslexic-charactersheets/pages#7]
Pathfinder skald has no spell page

**Comment by marcus-downing** [comment]
Good point. I'll fix that.

**Comment by myrrien** [comment]
still not working for me

**Comment by marcus-downing** [comment]
It'll be fixed in the next release. If time allows, that'll be this weekend.

**Comment by myrrien** [comment]
I'm sorry for disturbing you then

2018-02-27 20:49 GMT+01:00 Marcus Downing <notifications@github.com>:
