### ISSUE TITLE
Solarian: Zenith Revelations Missing, Expertise Talent Instead

### ISSUE THREAD

**Issue by Ravien** [dyslexic-charactersheets/pages#9]
As Title - Solarian Zenith Revelations are missing, and instead we have the Envoy's expertise talent section with the correct level blocks.

These should likely be displayed similarly to Supernova/Black Hole, but blank because there's a choice. 9th level and 17th level both give 1 revelation for Grav/Photon EACH, so two revelations at each of those levels.

COM note: These are technically optional, since a solarian can now discard one of these sets to get a second solar manifestation (out of the 4 now available, adding shield and flare), but this would be an uncommon choice

**Comment by marcus-downing** [comment]
Fixed.

I'm not going to be adding the extra Solar Manifestations from COM for the time being.
